### ISSUE TITLE
Add optional language to project types

### ISSUE THREAD

**Issue by michaelmior** [cmu-db/cmdbac#17]
It seems like the crawlers could potentially be much more efficient if the project types had an association language where appropriate (i.e. Python for Django, Groovy for Grails, etc.) Currently there are a lot of projects in the database that aren't related at all and this could likely help cut back on that.

**Comment by apavlo** [comment]
This is what the `valid_project` parameter is supposed to do. We keep all of the repos that we find in the database to prevent the crawler from pulling them down over and over again.

**Comment by michaelmior** [comment]
Got it. It seems then that I should change the repositories API to implicitly filter on `valid_project`.

**Comment by michaelmior** [comment]
@apavlo It looks like there's not a straightforward way to limit results to those with `valid_project = True` by default but still allow manual specification of `valid_project = False`. Is it reasonable to just force `valid_project = True` for the API for now? I think limiting to valid projects is much more useful than the option of retrieving invalid projects.

**Comment by apavlo** [comment]
Yes force it. Nobody should be able to see the invalid ones.
